{% set name = "pygifsicle" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygifsicle-{{ version }}.tar.gz
  sha256: 506ae0e4c76992a4fd6097da2d3f224a869ad504879fb1191d6af96c3d394ef8
  patches:
    - remove_package_manager_installs.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - setuptools
    - python >=3.6
    - pip
  run:
    - setuptools
    - python >=3.6
    - support_developer >=1.0.5
    - gifsicle

test:
  imports:
    - pygifsicle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LucaCappelletti94/pygifsicle
  summary: Python package wrapping the gifsicle library for editing and optimizing gifs.
  license: MIT
  license_file: 
    - LICENSE

extra:
  recipe-maintainers:
    - hmacdope
    - mikemhenry
